In [18]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples *class_0_ratio)
n_class_1 = n_samples - n_class_0

In [19]:
n_class_0,n_class_1

(900, 100)

In [20]:
pip install pandas

Requirement already satisfied: pandas in s:\AIML Courses\venv\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in s:\AIML Courses\venv\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in s:\AIML Courses\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in s:\AIML Courses\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in s:\AIML Courses\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2': np.random.normal(loc=0,scale=1,size=n_class_0),
    'target': [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1,size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1,size=n_class_1),
    'target':  [1]*n_class_1
})

In [22]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [23]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [24]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [25]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

UPSAMPLING

In [26]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [27]:
# pip install sklearn.utils

In [28]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority,replace=True,
                               n_samples=len(df_majority),
                               random_state = 1
                               )

In [29]:
df_minority_upsampled.shape

(900, 3)

In [30]:
df_minority_upsampled.head()

     feature_1  feature_2  target
937   1.068404   3.343388       1
912   2.834499   2.773754       1
972   2.181974   2.162665       1
909   3.239635   1.361938       1
975   2.192449   3.566033       1

In [31]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [42]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

UPSAMPLING

In [33]:
df_majority=df[df['target']==0]
df_minority=df[df['target']==1]

In [34]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,replace=False,
                               n_samples=len(df_minority),
                               random_state = 1
                               )

In [35]:
df_majority_downsampled.shape

(100, 3)

In [36]:
df_majority_downsampled.head()

     feature_1  feature_2  target
860   0.304515  -0.759475       0
880  -0.475648  -1.031913       0
874  -0.824501  -1.030322       0
780  -0.197236   0.215370       0
525   0.412819   0.191438       0

In [43]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled])
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64